# Generated by Django 5.1.4 on 2025-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label_en', models.CharField(max_length=100)),
                ('label_fr', models.CharField(max_length=100)),
            ],
        ),
    ]
